language: python
services:
  - docker

build:
  - docker build . -t benno001/bandit-demo

lint:
  - docker run --rm -i hadolint/hadolint < Dockerfile

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master