dist: trusty

services:
  - docker

jobs:
  include:
    - stage: lint
      script: docker run --rm -i hadolint/hadolint < Dockerfile
    - stage: build and push
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build . -t benno001/bandit-demo:latest
        - docker push benno001/bandit-demo:latest
      if: branch = master
      