dist: trusty

services:
  - docker

jobs:
  include:
    - stage: lint
      script: docker run --rm -i hadolint/hadolint < Dockerfile
    - stage: build
      script: docker build . -t benno001/bandit-demo
    - stage: deploy
      script: bash docker_push.sh
      if: branch = master